In [1]:
import pandas as pd
pd.set_option('display.max_colwidth', 100)

In [2]:
raw_output = 'resources/crawled_jd.json'
sum_output = 'resources/distilled_jd.json'

In [3]:
raw = pd.read_json(raw_output)

In [4]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 4 columns):
title      682 non-null object
link       682 non-null object
company    283 non-null object
descr      489 non-null object
dtypes: object(4)
memory usage: 21.4+ KB

In [5]:
raw[['title','descr']]

,title,descr
0,Junior Software Developer,NaN
1,Python Web/App Developer and Programmer,"We are currently seeking a Web/App Developer and Programmer with experience fluent in PHP, MySQL..."
2,Software Developer,NaN
3,Python API Developer,"Employer: Relevance LabLocation: Toronto, OntarioTerms of Employment: Permanent/Full TimeSalary:..."
4,Python Developer,Minimum Requirements:Python Developer InternMinimum Requirements:1 year PythonFamiliarity with G...
...,...,...
677,Python Developer,"Elephant (https://tripelephant.breezy.hr/)Python DeveloperFull-Time in Toronto, ON - Mid LevelTr..."
678,C++ Developer,What is the opportunity?This Developer role works within the electronic market making space at R...
679,Senior Developer (C# / Python / Matlab),What is the opportunity?As a Senior Developer on the Investment Platforms team in RBC Global Ass...
680,Database Developer,NaN
681,Senior Python Developer,About the OpportunityThis role will work on new features and R&D for a large high-volume transac...

In [6]:
summary = pd.read_json(sum_output)

In [7]:
summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 489 entries, 0 to 488
Data columns (total 5 columns):
title              489 non-null object
company            169 non-null object
descr_top_words    489 non-null object
descr_summ         489 non-null object
link               489 non-null object
dtypes: object(5)
memory usage: 19.2+ KB

In [8]:
summary[['title','descr_top_words','descr_summ']]

,title,descr_top_words,descr_summ
0,Python Web/App Developer and Programmer,"[applications, programming, code, learning, software, content, problems, technical, webapp, php]",[looking ambitious confident individual attentive details strong work ethic working part team in...
1,Python API Developer,"[python, deployment, implementing, application, build, eligible, benefits, ensuring, cloud, runn...","[eligible medical benefits, dental benefits rrsp contributions.hours work: 40 hours/weekcontact:..."
2,Python Developer,"[code, reviews, minimum, requirementspython, developer, internminimum, requirements1, year, pyth...",[)job qualifications:additional requirements:ui development using pyside2 / pyqt5experience linu...
3,Junior Software Developer,"[different, technology, care, design, future, building, solutions, every, healthcare, looking]","[software developer care product building, much care technical details it, come join us.you work..."
4,Python Back-end Developer,"[planet, ops, looking, web, fastpaced, growing, us, interpersonal, inc, leading]",[challenge find revenue model works established winning strategy need people help us executeteam...
...,...,...,...
484,Economist,"[economic, market, candidate, range, advice, energy, analysis, policy, arup, better]",[candidate also provide support guidance junior team members day day basis contribute teams lear...
485,Python Developer,"[marketing, python, api, ads, developer, google, bing, facebook, worked, apache]","[),website analysis affiliate marketing properties, administration various tools.python develope..."
486,C++ Developer,"[electronic, making, requirements, eg, market, capital, markets, existing, trading, platforms]",[requirements may include:trading algorithmsrisk hedging algorithmstrading platform infrastructu...
487,Senior Developer (C# / Python / Matlab),"[investment, technology, developer, rbc, teams, deliver, solutions, analytics, cloud, devops]",[opportunity?as senior developer investment platforms team rbc global asset management toronto o...
488,Senior Python Developer,"[highvolume, application, python, opportunitythis, features, rd, large, transactional, platform,...",[opportunitythis role work new features r&d large high-volume transactional application platform...